version: '3.1'

services:

  db:
    image: postgres
    restart: always
    volumes: 
      - ./pgdb:/var/lib/postgresql/data
    ports: 
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: testdbuser
      POSTGRES_DB: testdb

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080