# Generated by Django 4.0.4 on 2022-06-25 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=55)),
                ('company', models.CharField(max_length=20)),
                ('adress', models.CharField(max_length=55)),
                ('adress_2', models.CharField(max_length=4)),
                ('telephone', models.CharField(max_length=55)),
                ('comment', models.TextField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
