# Generated by Django 4.0.4 on 2022-07-31 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_categories_title_az_categories_title_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_az',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_en',
        ),
    ]
