# Generated by Django 4.0.7 on 2022-08-30 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_product_price_az_remove_product_price_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='field_name',
            field=models.ImageField(default='', upload_to=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.discount'),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
