# Generated by Django 4.0.7 on 2022-09-03 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_field_name_alter_product_discount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog_comment',
            options={'verbose_name': 'Blog Comment', 'verbose_name_plural': 'Blog Comments'},
        ),
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='productbrand',
            options={'verbose_name': 'Product Brand', 'verbose_name_plural': 'Product Brands'},
        ),
        migrations.AlterModelOptions(
            name='productpropertievalue',
            options={'verbose_name': 'Product Property Value', 'verbose_name_plural': 'Product Property Values'},
        ),
        migrations.AlterModelOptions(
            name='productreview',
            options={'verbose_name': 'Product Review', 'verbose_name_plural': 'Product Reviews'},
        ),
        migrations.AlterModelOptions(
            name='propertie',
            options={'verbose_name': 'Property', 'verbose_name_plural': 'Properties'},
        ),
        migrations.AlterModelOptions(
            name='propertievalue',
            options={'verbose_name': 'Property Value', 'verbose_name_plural': 'Property Values'},
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
