# Generated by Django 4.1.7 on 2023-03-18 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blog_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='description',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
