# Generated by Django 4.0.7 on 2022-09-03 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_alter_basketitem_options_basket_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basketitem',
            options={},
        ),
        migrations.RemoveField(
            model_name='basket',
            name='user',
        ),
        migrations.AddField(
            model_name='basketitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
