# Generated by Django 4.0.7 on 2022-09-03 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_basket_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketitem',
            name='price',
        ),
    ]
