# Generated by Django 3.2.6 on 2021-11-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('order', '0007_auto_20211114_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='product',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='product',
            field=models.ManyToManyField(related_name='wishlist_products', to='products.Product'),
        ),
    ]
