# Generated by Django 3.2.6 on 2021-11-20 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_auto_20211120_0813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingaddress',
            name='state',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='state',
        ),
    ]
