# Generated by Django 3.2.6 on 2021-11-21 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_auto_20211120_0815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingaddress',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='is_default',
        ),
    ]
