# Generated by Django 3.2.6 on 2021-11-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_auto_20211122_0814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='basket',
        ),
        migrations.AddField(
            model_name='order',
            name='basket_items',
            field=models.ManyToManyField(to='order.BasketItem'),
        ),
    ]
