# Generated by Django 3.2.6 on 2021-11-22 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_auto_20211122_0825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='basket_items',
        ),
        migrations.AddField(
            model_name='order',
            name='basket_items',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.basketitem'),
        ),
    ]
