# Generated by Django 3.2.6 on 2021-11-22 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_auto_20211122_0834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='basket_items',
        ),
        migrations.AddField(
            model_name='order',
            name='basket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.basket'),
        ),
    ]
